[green_agent]
agentbeats_id = "019bb72e-8276-7d22-92d9-41c57a5c936e"
env = { DATASET_ID = "dapumptu/usaco_benchmark" }

[[participants]]
agentbeats_id = "019bbc93-5379-7761-8809-1fe8de143f47"
name = "agent"
env = { SAMBANOVA_API_KEY = "${SAMBANOVA_API_KEY}" }

[config]
