[green_agent]
agentbeats_id = "019bb72e-8276-7d22-92d9-41c57a5c936e"
env = { DATASET_ID = "dapumptu/usaco_benchmark" }

[[participants]]
agentbeats_id = "019bbc93-5379-7761-8809-1fe8de143f47"
name = "agent"
env = { BASE_URL = "https://api.sambanova.ai/v1", API_KEY = "${API_KEY}", MODEL_ID = "Meta-Llama-3.3-70B-Instruct" }

[config]
